favicon: /img/favicon.png
avatar: /img/avatar.jpg
author: 'Zongjie Li'
author_bio: 'Ph.D. Candidate, HKUST & ETH Zurich'
since: 2021

menu:
  About: /#about
  Education: /#education
  Publications: /#publications
  Honors: /#honors
  Service: /#service
